Fix issues with AudioInUI
synamedia-senza/unified-player pull request #3
Opened 2024-11-19 14:51 UTC by jzahtz

2024-11-20 09:15 UTC, jzahtz commented on webpack.config.js
> +    devServer: {
Done, thanks

2024-11-20 09:15 UTC, jzahtz commented
@azamlerc Let me know if you have any comments.

2024-12-02 16:16 UTC, azamlerc commented on index.js
> +import {init, lifecycle, uiReady} from "senza-sdk";
I would prefer to not require that the app import the lifecycle object. That was quite intentional.

2024-12-02 16:16 UTC, azamlerc commented on index.js
> +    unifiedPlayer.isInRemotePlayback = state === "background" || state === "inTransitionToBackground";
Can the unified player take care of initializing its own state in its own constructor?

2024-12-02 16:18 UTC, azamlerc requested changes
I would prefer that the app does not import lifecycle, and that the UnifiedPlayer class can initialize its own state in its constructor rather than requiring the app to perform this step. We want to strictly minimize the amount of code in index.js.

2024-12-02 16:52 UTC, jzahtz commented on index.js
> +    unifiedPlayer.isInRemotePlayback = state === "background" || state === "inTransitionToBackground";
yes it can and was thinking of doing that. But, you still have an edge case where the index.js needs to wait until the UnifiedPlayer is initialized (including this isInRemotePlayback flag). So, if togglePlayback is called, the index would be using the proper value.

2024-12-03 07:55 UTC, jzahtz commented
> I would prefer that the app does not import lifecycle, and that the UnifiedPlayer class can initialize its own state in its constructor rather than requiring the app to perform this step. We want to strictly minimize the amount of code in index.js.

@azamlerc @amotzte 
Based on your comments, I switched to a "lazy load" implementation where we can guarantee that we have an updated state when coming back from release. This requires moving the togglePlay, Skip, playPause into Unified which I thought makes sense.
I understand that you are doing a refactoring for the shaka subclass. But, this PR fixes the uiState issue and isn't really related to your changes.
Please let me know what you think? Thanks.

2024-12-04 22:09 UTC, azamlerc approved these changes

2024-12-04 22:09 UTC, merged